const dummyData = [
  {
    class_name: "A Class",
    class_type: "Kickboxing",
    class_time: "7:00 am",
    class_date: "Aug 2",
    class_duration: "30 Minutes",
    class_intensity_level: "Low",
    class_location: "Garage",
    number_of_registered_attendees: 6,
    max_class_size: 15,
    id: 1,
  },
  {
    class_name: "B Class",
    class_type: "Crossfit",
    class_time: "9:00 am",
    class_date: "Aug 3",
    class_duration: "45 Minutes",
    class_intensity_level: "Medium",
    class_location: "Garage",
    number_of_registered_attendees: 6,
    max_class_size: 15,
    id: 2,
  },
  {
    class_name: "C Class",
    class_type: "Crossfit",
    class_time: "9:00 am",
    class_date: "Aug 3",
    class_duration: "45 Minutes",
    class_intensity_level: "Medium",
    class_location: "Garage",
    number_of_registered_attendees: 6,
    max_class_size: 15,
    id: 3,
  },
  {
    class_name: "D Class",
    class_type: "Kickboxing",
    class_time: "7:00 am",
    class_date: "Aug 2",
    class_duration: "30 Minutes",
    class_intensity_level: "Low",
    class_location: "Garage",
    number_of_registered_attendees: 6,
    max_class_size: 15,
    id: 4,
  },
  {
    class_name: "E Class",
    class_type: "Kickboxing",
    class_time: "7:00 am",
    class_date: "Aug 2",
    class_duration: "30 Minutes",
    class_intensity_level: "Low",
    class_location: "Garage",
    number_of_registered_attendees: 4,
    max_class_size: 15,
    id: 5,
  },
  {
    class_name: "F Class",
    class_type: "Kickboxing",
    class_time: "7:00 am",
    class_date: "Aug 2",
    class_duration: "30 Minutes",
    class_intensity_level: "Low",
    class_location: "Garage",
    number_of_registered_attendees: 7,
    max_class_size: 15,
    id: 6,
  },
  {
    class_name: "G Class",
    class_type: "Kickboxing",
    class_time: "7:00 am",
    class_date: "Aug 2",
    class_duration: "30 Minutes",
    class_intensity_level: "Low",
    class_location: "Garage",
    number_of_registered_attendees: 6,
    max_class_size: 15,
    id: 7,
  },
];

export default dummyData;
